# Generated by Django 3.2.16 on 2023-02-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmtapi',
            name='common_flag',
        ),
        migrations.AddField(
            model_name='cmtapi',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
