# Generated by Django 3.2.16 on 2023-02-17 03:28

from django.db import migrations, models
import tcms.core.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0004_cmtapidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=8, verbose_name='类型代码')),
                ('type_desc', models.CharField(max_length=16, verbose_name='类型描述')),
            ],
            options={
                'db_table': 'cmt_api_type',
            },
            bases=(models.Model, tcms.core.models.base.UrlMixin),
        ),
    ]
