# Generated by Django 3.2.16 on 2023-02-17 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0005_apitype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmtapi',
            name='api_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='cmt.apitype'),
        ),
    ]
