# Generated by Django 3.2.16 on 2023-02-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tcms.core.models.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmt', '0007_auto_20230217_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmtCaseRelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_desc', models.CharField(max_length=16, verbose_name='关联类型描述')),
            ],
            options={
                'db_table': 'cmt_case_rel_type',
            },
            bases=(models.Model, tcms.core.models.base.UrlMixin),
        ),
        migrations.CreateModel(
            name='CmtCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32, verbose_name='案例描述')),
                ('arrange', models.CharField(max_length=64, null=True, verbose_name='关联的编排')),
                ('tag', models.CharField(max_length=32, null=True, verbose_name='Tag')),
                ('active_flag', models.BooleanField(default=True)),
                ('input', models.TextField(blank=True, null=True, verbose_name='请求信息')),
                ('output', models.TextField(blank=True, null=True, verbose_name='返回信息')),
                ('pass_rule', models.CharField(max_length=64, null=True, verbose_name='通过规则')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cmt.cmtapi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycases', to=settings.AUTH_USER_MODEL)),
                ('rel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cmt.cmtcasereltype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cmt.cmtservice')),
            ],
            options={
                'db_table': 'cmt_case',
            },
            bases=(models.Model, tcms.core.models.base.UrlMixin),
        ),
    ]
