# Generated by Django 3.2.16 on 2023-02-21 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tcms.core.models.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmt', '0008_cmtcase_cmtcasereltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmtArrange',
            fields=[
                ('arrange_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32, verbose_name='编排描述')),
                ('active_flag', models.BooleanField(default=True)),
                ('input', models.TextField(blank=True, null=True, verbose_name='请求信息')),
                ('output', models.TextField(blank=True, null=True, verbose_name='返回信息')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='create_date')),
            ],
            options={
                'db_table': 'cmt_arrange',
            },
            bases=(models.Model, tcms.core.models.base.UrlMixin),
        ),
        migrations.CreateModel(
            name='CmtArrangeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.cmtapi')),
                ('arrange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.cmtarrange')),
            ],
            options={
                'db_table': 'cmt_arrange_api',
            },
            bases=(models.Model, tcms.core.models.base.UrlMixin),
        ),
        migrations.AddField(
            model_name='cmtarrange',
            name='apis',
            field=models.ManyToManyField(related_name='arranges', through='cmt.CmtArrangeApi', to='cmt.CmtApi', verbose_name='包含的API'),
        ),
        migrations.AddField(
            model_name='cmtarrange',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myarranges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmtarrange',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arranges', to='cmt.cmtservice'),
        ),
    ]
