# Generated by Django 3.2.16 on 2023-02-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0009_auto_20230221_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtcase',
            name='arrange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arranges', to='cmt.cmtarrange'),
        ),
    ]
