# Generated by Django 3.2.16 on 2023-02-21 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0010_alter_cmtcase_arrange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmtarrange',
            name='apis',
        ),
        migrations.AddField(
            model_name='cmtarrange',
            name='apis',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='编排API'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CmtArrangeApi',
        ),
    ]
