# Generated by Django 3.2.16 on 2023-02-23 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tcms.core.models.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmt', '0011_auto_20230221_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmtPublicDef',
            fields=[
                ('public_def_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32, verbose_name='公共请求定义描述')),
                ('active_flag', models.BooleanField(default=True)),
                ('input', models.TextField(blank=True, null=True, verbose_name='请求信息')),
                ('output', models.TextField(blank=True, null=True, verbose_name='返回信息')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mine_public_def', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_def', to='cmt.cmtservice')),
            ],
            options={
                'db_table': 'cmt_public_def',
            },
            bases=(models.Model, tcms.core.models.base.UrlMixin),
        ),
        migrations.CreateModel(
            name='CmtPublicData',
            fields=[
                ('public_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32, verbose_name='公共请求数据描述')),
                ('active_flag', models.BooleanField(default=True)),
                ('input', models.TextField(blank=True, null=True, verbose_name='请求信息')),
                ('output', models.TextField(blank=True, null=True, verbose_name='返回信息')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mine_public_data', to=settings.AUTH_USER_MODEL)),
                ('public_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_data', to='cmt.cmtpublicdef')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_data', to='cmt.cmtservice')),
            ],
            options={
                'db_table': 'cmt_public_data',
            },
            bases=(models.Model, tcms.core.models.base.UrlMixin),
        ),
    ]
