# Generated by Django 3.2.16 on 2023-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0013_cmtcase_public_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtarrange',
            name='apis',
            field=models.TextField(verbose_name='编排API'),
        ),
    ]
